### PR TITLE
Gracefully handle owee failures in Elf.addr_table

### LINKED ISSUE #191: Failed to decode perf.data: monitor.ml.Error (Invalid_argument "index out of bounds")
- What happened?

```
$ sudo ./magic-trace attach -pid 2098
[ Attached. Press Ctrl-C to stop recording. ]
^C[ Got signal, detaching... ]
[ Snapshot taken. ]
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 4.206 MB /tmp/magic_trace.tmp.3aa1a4/perf.data ]
[ Finished recording. ]
[ Decoding, this takes a while... ]
(monitor.ml.Error (Invalid_argument "index out of bounds")
 ("Raised by primitive operation at Owee_buf.Read.u16 in file \"src/owee_buf.ml\", line 68, characters 43-68"
  "Called from Owee_debug_line.read_header in file \"src/owee_debug_line.ml\", line 187, characters 16-30"
  "Called from Magic_trace_core__Elf.addr_table.(fun).load_table_next in file \"core/elf.ml\", line 151, characters 14-75"
  "Called from Base__Option.iter in file \"src/option.ml\" (inlined), line 68, characters 14-17"
  "Called from Magic_trace_core__Elf.addr_table in file \"core/elf.ml\", line 135, characters 2-1023"
  "Called from Base__Option.map in file \"src/option.ml\", line 226, characters 19-24"
  "Called from Magic_trace_lib__Trace.Make_commands.decode_to_trace.(fun) in file \"src/trace.ml\", line 143, characters 25-57"
  "Called from Magic_trace_lib__Tracing_tool_output.write_and_maybe_serve in file \"src/tracing_tool_output.ml\", line 156, characters 17-20"
  "Called from Async_kernel__Deferred0.bind.(fun) in file \"src/deferred0.ml\", line 54, characters 64-69"
  "Called from Async_kernel__Job_queue.run_jobs in file \"src/job_queue.ml\", line 167, characters 6-47"
  "Caught by monitor Monitor.protect"))
```

- How can we, magic-trace developers, reproduce the issue you're seeing?

maybe trace a program running in docker?

- What version of perf userspace tools are you running? 

4.15.18

- What CPU do you have? 

Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz

### PR DESCRIPTION
**Pull request by cgaebel**
Owee shouldn't have the ability to crash magic-trace. It's ~always preferably to not display debug info instead of crashing on users.

### CODE REVIEW

**Review by Xyene — APPROVED** [review]
LGTM, but we should probably warn when this happens, to disambiguate between "don't have debug info installed at all" and "have debug info but magic-trace can't interpret it"?

**Comment by cgaebel** [comment]
I reworked this, please take another look.

File: src/trace.ml [hunk 1]
```diff
@@ -140,7 +144,20 @@ module Make_commands (Backend : Backend_intf.S) = struct
...
           |> [%of_sexp: Hits_file.t]
         in
-        let debug_info = Option.map elf ~f:Elf.addr_table in
+        let debug_info =
+          match
+            Option.bind elf ~f:(fun elf -> Option.try_with (fun () -> Elf.addr_table elf))
+          with
+          | None ->
+            eprintf
+              "Warning: Debug info is unavaliable, so filenames and line numbers will \
```
Comment (Xyene) [inline src/trace.ml:153]:
```suggestion
              "Warning: Debug info is unavailable, so filenames and line numbers will \
```

**Review by Xyene — APPROVED** [review]
Otherwise LGTM, thanks.
